[DEVOPS-428] fixing alarms for RDS in aws prod
notarize/terraform-aws-rds pull request #12
Opened 2021-05-17 18:54 UTC by myrabokhari

##### Corresponding Issue(s):
 - PRs should have a corresponding issue. If no issue exists, provide details in the **Reason for Change(s)** section

##### Summary of change(s):

##### Reason for Change(s):

- If a bug, describe error scenario, including expected behavior and actual behavior.

- If an enhancement, describe the use case and the perceived benefit(s).

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:

##### Does this update/change involve issues with other external modules? If so, please describe the scenario.

##### If input variables or output variables have changed or has been added, have you updated the README?

##### Do examples need to be updated based on changes?

##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

2021-05-17 18:56 UTC, myrabokhari commented
@gotrevor-notarize this is for fixing the current plan in aws prod TF. 
Some changes to sync with the current rds alarms, so that TF gives no changes in TF plan. Should be good to go!

2021-05-18 13:14 UTC, gotrevor-notarize commented on main.tf
> +  source = "git@github.com:/notarize/terraform-aws-cloudwatch_alarm.git?ref=v.0.0.2"
Is there a reason to only go up to 0.0.2 here, when you go to 0.0.6 below, in the same module?

2021-05-18 13:14 UTC, gotrevor-notarize requested changes
Clarification on why you include different revisions of the same module.

2021-05-18 14:04 UTC, myrabokhari commented
> Clarification on why you include different revisions of the same module.

it actually depends on the details/configuration sof the version. In some alarms the old version sync with their current configuration and with some alarms it doesn’t (it shows changes in the plan). 
So to sync all the alarms correctly I had to do that.

2021-05-18 16:13 UTC, gotrevor-notarize approved these changes
Looking forward to a path toward using the latest version of various module. For now, :shipit:

2021-05-18 16:22 UTC, merged